FROM python:3.11-slim

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install gcc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

WORKDIR /app

COPY stac_fastapi/mongo /app/stac_fastapi/mongo
COPY LICENSE /app/
COPY README.md /app/

RUN --mount=type=bind,source=setup.py,target=setup.py \
    pip install --upgrade pip && \
    pip install --no-cache-dir .[server] && \
    pip uninstall -y wheel && \
    rm -r build && \
    rm -r stac_fastapi_mongo.egg-info 

EXPOSE 8080

CMD ["uvicorn", "stac_fastapi.mongo.app:app", "--host", "0.0.0.0", "--port", "8080"]
